// Generated by gencpp from file traj_utils/Assignment.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_ASSIGNMENT_H
#define TRAJ_UTILS_MESSAGE_ASSIGNMENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct Assignment_
{
  typedef Assignment_<ContainerAllocator> Type;

  Assignment_()
    : assignment()  {
      assignment.assign(0);
  }
  Assignment_(const ContainerAllocator& _alloc)
    : assignment()  {
  (void)_alloc;
      assignment.assign(0);
  }



   typedef boost::array<uint32_t, 10>  _assignment_type;
  _assignment_type assignment;





  typedef boost::shared_ptr< ::traj_utils::Assignment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::Assignment_<ContainerAllocator> const> ConstPtr;

}; // struct Assignment_

typedef ::traj_utils::Assignment_<std::allocator<void> > Assignment;

typedef boost::shared_ptr< ::traj_utils::Assignment > AssignmentPtr;
typedef boost::shared_ptr< ::traj_utils::Assignment const> AssignmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::Assignment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::Assignment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::Assignment_<ContainerAllocator1> & lhs, const ::traj_utils::Assignment_<ContainerAllocator2> & rhs)
{
  return lhs.assignment == rhs.assignment;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::Assignment_<ContainerAllocator1> & lhs, const ::traj_utils::Assignment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::Assignment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::Assignment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::Assignment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::Assignment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::Assignment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::Assignment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::Assignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc09302ffe2353e20a7ca4e9c550e719";
  }

  static const char* value(const ::traj_utils::Assignment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc09302ffe2353e2ULL;
  static const uint64_t static_value2 = 0x0a7ca4e9c550e719ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::Assignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/Assignment";
  }

  static const char* value(const ::traj_utils::Assignment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::Assignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[10] assignment\n"
;
  }

  static const char* value(const ::traj_utils::Assignment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::Assignment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.assignment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Assignment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::Assignment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::Assignment_<ContainerAllocator>& v)
  {
    s << indent << "assignment[]" << std::endl;
    for (size_t i = 0; i < v.assignment.size(); ++i)
    {
      s << indent << "  assignment[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.assignment[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_ASSIGNMENT_H
