// Generated by gencpp from file tracking_msgs/TargetObservation.msg
// DO NOT EDIT!


#ifndef TRACKING_MSGS_MESSAGE_TARGETOBSERVATION_H
#define TRACKING_MSGS_MESSAGE_TARGETOBSERVATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <nav_msgs/Odometry.h>

namespace tracking_msgs
{
template <class ContainerAllocator>
struct TargetObservation_
{
  typedef TargetObservation_<ContainerAllocator> Type;

  TargetObservation_()
    : header()
    , image_pos()
    , depth(0.0)
    , drone_odom()  {
    }
  TargetObservation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_pos(_alloc)
    , depth(0.0)
    , drone_odom(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _image_pos_type;
  _image_pos_type image_pos;

   typedef double _depth_type;
  _depth_type depth;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _drone_odom_type;
  _drone_odom_type drone_odom;





  typedef boost::shared_ptr< ::tracking_msgs::TargetObservation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracking_msgs::TargetObservation_<ContainerAllocator> const> ConstPtr;

}; // struct TargetObservation_

typedef ::tracking_msgs::TargetObservation_<std::allocator<void> > TargetObservation;

typedef boost::shared_ptr< ::tracking_msgs::TargetObservation > TargetObservationPtr;
typedef boost::shared_ptr< ::tracking_msgs::TargetObservation const> TargetObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracking_msgs::TargetObservation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracking_msgs::TargetObservation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tracking_msgs::TargetObservation_<ContainerAllocator1> & lhs, const ::tracking_msgs::TargetObservation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_pos == rhs.image_pos &&
    lhs.depth == rhs.depth &&
    lhs.drone_odom == rhs.drone_odom;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tracking_msgs::TargetObservation_<ContainerAllocator1> & lhs, const ::tracking_msgs::TargetObservation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tracking_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracking_msgs::TargetObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_msgs::TargetObservation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_msgs::TargetObservation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b05b044b9de45d04297a9cb0b1fd945";
  }

  static const char* value(const ::tracking_msgs::TargetObservation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b05b044b9de45d0ULL;
  static const uint64_t static_value2 = 0x4297a9cb0b1fd945ULL;
};

template<class ContainerAllocator>
struct DataType< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracking_msgs/TargetObservation";
  }

  static const char* value(const ::tracking_msgs::TargetObservation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point image_pos  # 目标在图像中的位置 (u,v)\n"
"float64 depth  # 深度估计\n"
"nav_msgs/Odometry drone_odom  # 无人机姿态\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tracking_msgs::TargetObservation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_pos);
      stream.next(m.depth);
      stream.next(m.drone_odom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetObservation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracking_msgs::TargetObservation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracking_msgs::TargetObservation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.image_pos);
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
    s << indent << "drone_odom: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.drone_odom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKING_MSGS_MESSAGE_TARGETOBSERVATION_H
